### ISSUE TITLE
UnboundLocalError: local variable 'range' referenced before assignment

### ISSUE THREAD

**Issue by svenikea** [ehmatthes/pcc_3e#6]
Hi Eric,

I was doing some exercises on Chapter 9 Classes, and in the exercise 9.9 I was getting this error in the method `get_range` 
```
UnboundLocalError: local variable 'range' referenced before assignment`
```
I think this is a variable scope issue, the `range` variable only available inside the if statement  as it's a local variable. Anyway, I was able to get it to work by doing some small changes to the class Battery like this

```
    def __init__(self, battery_size=40):
        """Initialize the battery's attributes."""
        self.battery_size = battery_size
        self.range = 0

        if self.battery_size == 40:
            self.range = 150
        if self.battery_size == 65:
            self.range = 225
        if self.battery_size == 100:
            self.range = 300
        print(f"This car can go about {self.range} miles on a full charge.")
```

Please let me know if you have better solution than mine.

**Comment by ehmatthes** [comment]
Hi. This isn't really a scope issue, it's more a matter of how we're modeling the possible battery sizes for the car. Here's the `get_range()` [method](https://github.com/ehmatthes/pcc_3e/blob/main/chapter_09/electric_car.py#L43) I've shown:

```python
    def get_range(self):
        """Print a statement about the range this battery provides."""
        if self.battery_size == 40:
            range = 150
        elif self.battery_size == 65:
            range = 225

        print(f"This car can go about {range} miles on a full charge.")
```

First, `range` *is* a local variable here, because it's only used to report the range from this method. If you want to make it an attribute by attaching it to `self`, that's perfectly reasonable. But the main thing to see here is the structure of the conditional block. We only have an if-elif chain. There are only two battery sizes that work for this car: 40kWh and 65kWh.

I'm guessing your `updgrade_battery()` method included an option to upgrade to 100kWh. In that case, you would have to add an additional elif block to `get_range()` to report the range for that battery.

The main thing I don't like about initializing range to 0 is that it's not really meaningful. Electric cars with a functioning battery don't have a range of 0. If the owner has upgraded the battery to a size that's not recognized, the range would be unknown, not 0. That would be implemented by adding an else block that reports an unrecognized battery size.

Looking at this example again, an interesting solution gets away from if blocks. We could use a dictionary for this method:

```python
    def get_range(self):
        """Print a statement about the range this battery provides."""

        # battery_ranges = {battery_size: range}
        battery_ranges = {
            40: 150,
            65: 225
        }

        range = battery_ranges[self.battery_size]
        print(f"This car can go about {range} miles on a full charge.")
```

I wouldn't say this is better or worse than the if-block approach. Some people like conditional statements, others prefer dictionary lookups. With a long set of options, the dictionary approach is probably better. Adding support for a new battery is as simple as adding a single new entry in the dictionary.

One last note; if you're staying with the conditional approach, it's good to use if-elif-else when only one of the conditions can be true. In that structure the blocks stop executing as soon as the correct match is found. In a series of simple if blocks, every check is made even if the correct one has already been found.

Does that help?

**Comment by svenikea** [comment]
Hi Eric, 

Thank you for your wonderful analysis, yes of course using a dictionary in this scenario is **wayyy** better. And you were right I don't know why I declared `range = 0` in the first place it doesn't mean anything when we are trying to model a real-world object using class. 

Sorry for wasting your time.

**Comment by ehmatthes** [comment]
This wasn't a waste at all, it's a really interesting question that comes up when you implement an upgrade option that doesn't match what was originally written. I write a weekly newsletter about Python, and I'm going to write a post about some of the things this question raises.

I wrote this example years ago, and this is the first time I've thought to use a dictionary for the range lookup. I grew up on if statements, and didn't come across dictionaries until I started learning Python. I'm just starting to use them in place of short if-elif-else blocks. 

Thanks again for reaching out!
